import { useMemo, useState } from 'react'
import './App.css'
import AppHeader from './components/AppHeader'
import QuestionsPanel from './components/QuestionsPanel'
import Sidebar from './components/Sidebar'
import useAiServer from './hooks/useAiServer'
import { checkAnswerWithAi, extractPdfWithAi } from './services/aiService'
import { extractPdfText, fileToBase64 } from './services/pdfService'
import { normalizeChoice } from './utils/choices'
import { hasUnreadablePdfText, parseQuestions } from './utils/questionParser'
import { calculateStats, downloadAnswerSheet } from './utils/results'

function App() {
  const [fileName, setFileName] = useState('')
  const [rawText, setRawText] = useState('')
  const [questions, setQuestions] = useState([])
  const [answers, setAnswers] = useState({})
  const [pdfPayload, setPdfPayload] = useState(null)
  const [aiChecks, setAiChecks] = useState({})
  const [isAiLoading, setIsAiLoading] = useState(false)
  const [status, setStatus] = useState('Upload a PDF or paste question text.')
  const [isLoading, setIsLoading] = useState(false)
  const { aiConfigured, aiEnabled, aiStatus, setAiEnabled, setAiStatus } = useAiServer()

  const stats = useMemo(
    () => calculateStats(questions, answers, aiChecks),
    [aiChecks, answers, questions],
  )

  const resetQuiz = () => {
    setAnswers({})
    setAiChecks({})
  }

  const parseAndLoadQuestions = (text) => {
    const parsedQuestions = parseQuestions(text)
    setQuestions(parsedQuestions)
    resetQuiz()

    if (!text.trim()) {
      setStatus('No readable text found. If this is a scanned image PDF, OCR is needed first.')
      return parsedQuestions
    }

    if (!parsedQuestions.length) {
      if (hasUnreadablePdfText(text)) {
        setStatus(
          'PDF text is unreadable because of custom font encoding or scanned text. Try AI extract PDF, or use an OCR/Unicode PDF.',
        )
        return parsedQuestions
      }

      setStatus(
        'No objective questions found in the text. Use AI generate Q&A to read the PDF in its original language and create questions.',
      )
      return parsedQuestions
    }

    const missingKeys = parsedQuestions.filter((question) => !question.correctOption).length
    setStatus(
      missingKeys
        ? `${parsedQuestions.length} questions found. ${missingKeys} need an answer key.`
        : `${parsedQuestions.length} questions ready for checking.`,
    )
    return parsedQuestions
  }

  const extractQuestionsWithAi = async (payloadToExtract) => {
    if (!aiConfigured) {
      setAiStatus('Add GEMINI_API_KEY in .env and restart npm run api to use Google AI.')
      return
    }

    if (!payloadToExtract) {
      setAiStatus('Upload a PDF first, then AI can generate questions and answers from it.')
      return
    }

    setIsAiLoading(true)
    setAiStatus('Google AI is analyzing the PDF context and generating objective questions...')

    try {
      const payload = await extractPdfWithAi(payloadToExtract)
      const languageNote = payload.languageSummary ? ` Languages: ${payload.languageSummary}.` : ''
      const contextNote = payload.contextSummary ? ` Context: ${payload.contextSummary}` : ''

      setQuestions(payload.questions || [])
      resetQuiz()
      setStatus(
        payload.questions?.length
          ? `${payload.questions.length} objective questions generated by Google AI.${languageNote}${contextNote}`
          : 'Google AI could not generate questions from this PDF.',
      )
      setAiStatus(payload.notes || 'AI context analysis and question generation finished.')
    } catch (error) {
      setAiStatus(error.message)
    } finally {
      setIsAiLoading(false)
    }
  }

  const handleFile = async (event) => {
    const file = event.target.files?.[0]
    if (!file) return

    setIsLoading(true)
    setIsAiLoading(false)
    setFileName(file.name)
    setPdfPayload(null)
    setAiChecks({})
    setStatus(aiConfigured ? 'Preparing PDF for AI context analysis...' : 'Reading PDF text...')

    try {
      const base64 = await fileToBase64(file)
      const nextPdfPayload = {
        name: file.name,
        mimeType: file.type || 'application/pdf',
        data: base64,
      }
      setPdfPayload(nextPdfPayload)

      let text = ''
      try {
        text = await extractPdfText(file)
      } catch (textError) {
        text = ''
        setStatus(`Browser text extraction failed: ${textError.message}. AI can still analyze the PDF file directly.`)
      }

      setRawText(text)

      if (!aiConfigured) {
        setQuestions([])
        resetQuiz()
        setStatus('Google AI is not connected. Start npm run api, then upload the PDF again for language-aware question generation.')
        setAiStatus('PDF uploaded, but AI analysis needs the local server at http://127.0.0.1:8787.')
        return
      }

      setStatus('Asking Google AI to understand the PDF and create objective Q&A...')
      setIsLoading(false)
      await extractQuestionsWithAi(nextPdfPayload)
      return
    } catch (error) {
      setStatus(`PDF could not be read: ${error.message}`)
    } finally {
      setIsLoading(false)
    }
  }

  const askAiToExtractPdf = () => extractQuestionsWithAi(pdfPayload)

  const askAiToCheckAnswer = async (question, selectedOption) => {
    if (!aiConfigured) {
      setAiStatus('Add GEMINI_API_KEY in .env and restart npm run api to use Google AI.')
      return
    }

    setAiChecks((currentChecks) => ({
      ...currentChecks,
      [question.id]: {
        ...(currentChecks[question.id] || {}),
        status: 'checking',
      },
    }))
    setAiStatus(`Google AI is checking question ${question.sourceNumber || question.id}...`)

    try {
      const payload = await checkAnswerWithAi(question, selectedOption)

      setAiChecks((currentChecks) => ({
        ...currentChecks,
        [question.id]: {
          status: 'done',
          correctOption: normalizeChoice(payload.correctOption),
          explanation: payload.explanation,
          confidence: payload.confidence,
        },
      }))
      setAiStatus(`AI checked question ${question.sourceNumber || question.id}.`)
    } catch (error) {
      setAiChecks((currentChecks) => ({
        ...currentChecks,
        [question.id]: {
          ...(currentChecks[question.id] || {}),
          status: 'error',
          error: error.message,
        },
      }))
      setAiStatus(error.message)
    }
  }

  const handleAnswer = (questionId, optionKey) => {
    const question = questions.find((item) => item.id === questionId)

    setAnswers((currentAnswers) => ({
      ...currentAnswers,
      [questionId]: optionKey,
    }))

    if (question && aiEnabled && aiConfigured) {
      askAiToCheckAnswer(question, optionKey)
    }
  }

  return (
    <main className="min-h-screen bg-[#f4f8fb] text-[#1f2933]">
      <AppHeader onFileChange={handleFile} stats={stats} />

      <div className="mx-auto grid max-w-7xl gap-6 px-4 py-6 sm:px-6 lg:grid-cols-[360px_1fr] lg:px-8">
        <Sidebar
          aiConfigured={aiConfigured}
          aiEnabled={aiEnabled}
          aiStatus={aiStatus}
          fileName={fileName}
          isAiLoading={isAiLoading}
          isLoading={isLoading}
          onAiEnabledChange={setAiEnabled}
          onAiExtract={askAiToExtractPdf}
          onParse={() => parseAndLoadQuestions(rawText)}
          pdfPayload={pdfPayload}
          rawText={rawText}
          setRawText={setRawText}
          status={status}
        />
        <QuestionsPanel
          aiChecks={aiChecks}
          answers={answers}
          onAnswer={handleAnswer}
          onDownloadSheet={() => downloadAnswerSheet(questions, answers, aiChecks)}
          questions={questions}
        />
      </div>
    </main>
  )
}

export default App
